/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server_manager;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import org.snmp4j.CommunityTarget;
import org.snmp4j.PDU;
import org.snmp4j.Snmp;
import org.snmp4j.TransportMapping;
import org.snmp4j.mp.SnmpConstants;
import org.snmp4j.smi.Address;
import org.snmp4j.smi.GenericAddress;
import org.snmp4j.smi.OID;
import org.snmp4j.smi.OctetString;
import org.snmp4j.smi.UdpAddress;
import org.snmp4j.smi.VariableBinding;
import org.snmp4j.transport.DefaultUdpTransportMapping;

/**
 *
 * @author nenoxx
 */
public class Server_ManagerGUI extends javax.swing.JFrame {
    private TransportMapping transport;
    private SnmpListener listener;
    private Snmp snmp;
    private CommunityTarget target;
    private DefaultTableModel dtm;
    private String AdresseIP = "";
    private String[] OID = {""};
    
    /**
     * Creates new form Server_ManagerGUI
     */
    public Server_ManagerGUI() {
        initComponents();
        ButtonGroup.add(SetButton);
        ButtonGroup.add(GetNextButton);
        ButtonGroup.add(GetButton);
        SetTF.setEnabled(false);
        
        try 
        {
            transport = new DefaultUdpTransportMapping();
            transport.listen();
            
            snmp = new Snmp(transport);
            listener = new SnmpListener(snmp, (DefaultTableModel)jTable1.getModel());
            listener.LinkOIDField(OIDTF);
            target = new CommunityTarget();
            target.setRetries(2);
            target.setTimeout(1500);
            target.setVersion(SnmpConstants.version1);
            
        } 
        catch (IOException ex) 
        {
            showMessageDialog(this, "Erreur : " + ex, "Error", ERROR_MESSAGE);
        }
    }
    
    private boolean Trouve100(String s)
    {
        StringTokenizer st = new StringTokenizer(s, " ");
        
        while(st.hasMoreTokens())
        {
            String test = st.nextToken();
            int p = test.indexOf("%");
            int p100 = test.indexOf("100");
            if(p != -1 && p100 != -1)
                return true;
        }
        return false;
    }
    
    private boolean Ping()
    {
        boolean trouve = false;
        try 
        {
            //Test de la connexion
            Process p;
            String command = "ping -c 2 -w 1000 " + IPDestTF.getText();
            BufferedReader buffer;

            p = Runtime.getRuntime().exec(command);
            if(p == null)
                System.out.println("Erreur de ping");

            buffer = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            while((line = buffer.readLine()) != null) 
            {
                trouve = Trouve100(line); //Sous Linux -> 100% = 100% de packet loss <> Windows -> 100% = 0% packet loss
                if(trouve == true)
                {
                    showMessageDialog(this, "L'adresse " + IPDestTF.getText() + " ne repond pas.", "Error", ERROR_MESSAGE);
                    return true;
                }
            }
            buffer.close();
        } 
        catch (IOException ex) 
        {
            showMessageDialog(this, "Erreur Ping : " + ex, "Error", ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        IPDestLabel = new javax.swing.JLabel();
        IPDestTF = new javax.swing.JTextField();
        SetButton = new javax.swing.JRadioButton();
        GetButton = new javax.swing.JRadioButton();
        GoButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        GetNextButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Community = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OIDTF = new javax.swing.JTextField();
        SetTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IPDestLabel.setText("IP destination : ");

        IPDestTF.setText("127.0.0.1");

        SetButton.setText("SET");
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        GetButton.setText("GET");
        GetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetButtonActionPerformed(evt);
            }
        });

        GoButton.setText("C'est parti Jacky");
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });

        QuitButton.setText("Sortez-moi d'ici");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        GetNextButton.setText("GET-NEXT");
        GetNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNextButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name/OID", "Value", "Value", "IP"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Community :");

        Community.setText("2326ZAMD");

        jLabel2.setText("OID :");

        OIDTF.setText(".1.3.6.1.2.1.1.1.0");

        jLabel3.setText("Nouv. valeur :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IPDestLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IPDestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OIDTF)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Community, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(SetTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QuitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetNextButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPDestLabel)
                    .addComponent(IPDestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoButton)
                    .addComponent(jLabel1)
                    .addComponent(Community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuitButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(OIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SetTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetButton)
                    .addComponent(GetButton)
                    .addComponent(GetNextButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
        SetTF.setEnabled(true);
    }//GEN-LAST:event_SetButtonActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        AdresseIP = IPDestTF.getText() + "/161";
        OID = OIDTF.getText().substring(1).split("\\.");
        int[] stillOID = ToIntTab(OID);
        target.setCommunity(new OctetString(Community.getText()));
        Address targetIP = new UdpAddress(AdresseIP);
        target.setAddress(targetIP);
        PDU pdu = new PDU();
        boolean Selected = false;
        
        System.out.println("Tentative de ping de la machine distante...");
        if(!(Ping())){
            System.out.println("La machine distante est accessible !");
            try{
                if(SetButton.isSelected()){
                    pdu.setType(PDU.SET);
                    pdu.add(new VariableBinding(new OID(stillOID), new OctetString(SetTF.getText())));
                    snmp.set(pdu, target, null, listener);
                    Selected = true;
                }
                else{
                    if(GetButton.isSelected()){
                            pdu.setType(PDU.GET);
                            pdu.add(new VariableBinding(new OID(stillOID)));
                            snmp.get(pdu, target, null, listener);
                            Selected = true;
                    }
                    else{
                        if(GetNextButton.isSelected()){
                            pdu.setType(PDU.GETNEXT);
                            pdu.add(new VariableBinding(new OID(stillOID)));
                            snmp.send(pdu, target, null, listener);  
                            Selected = true;
                        }
                    }
                }
                if(Selected){
                    System.out.println("Requete SNMP envoyée à l'agent");
                    synchronized(snmp){
                        snmp.wait();
                    }
                }
            }
            catch (Exception ex) {
                System.out.println(ex.getLocalizedMessage());
            }
            
        }
    }//GEN-LAST:event_GoButtonActionPerformed
    
    private int[] ToIntTab(String[] str){
        if(str == null || str.length == 0)
            return null;
        
        int[] tmp = new int[str.length];
        for(int i = 0; i < str.length; i++)
            tmp[i] = Integer.parseInt(str[i]);
        
        return tmp;
    }
    
    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void GetNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNextButtonActionPerformed
        SetTF.setEnabled(false);
    }//GEN-LAST:event_GetNextButtonActionPerformed

    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetButtonActionPerformed
        SetTF.setEnabled(false);
    }//GEN-LAST:event_GetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_ManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JTextField Community;
    private javax.swing.JRadioButton GetButton;
    private javax.swing.JRadioButton GetNextButton;
    private javax.swing.JButton GoButton;
    private javax.swing.JLabel IPDestLabel;
    private javax.swing.JTextField IPDestTF;
    private javax.swing.JTextField OIDTF;
    private javax.swing.JButton QuitButton;
    private javax.swing.JRadioButton SetButton;
    private javax.swing.JTextField SetTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
