.SILENT :

ALL: Client Serveur

Client:	Client.cpp tcplib.h
	echo Creation de client...
	gcc Client.cpp -o Client

Serveur: Serveur.cpp tcplib.h
	echo Creation de serveur...
	gcc Serveur.cpp -o Serveur
